### ISSUE TITLE
Language choice?

### ISSUE THREAD

**Issue by Akurosia** [icykoneko/ff14-fish-tracker-app#1]
Is there a way to toogle the language?

**Comment by icykoneko** [comment]
Not at the moment; however, this wouldn't be impossible to do.  While the master data file is written using the English strings, everything is converted to IDs, then serialized into the data.js file.  So, technically, I could output any language's strings to that.

I did not take 118n into account when designing the front-end though.

**Comment by Akurosia** [comment]
thats nice to hear.

also is there a way to get the python version of saint? i looked for it (as it was mentioned in the readme) but i couldnt find it

**Comment by icykoneko** [comment]
Oh yea, I should upload it here.

**Comment by icykoneko** [comment]
I updated the repo to use submodules for the SainCoinach libraries.  Hopefully it works.  Keep in mind, I haven't updated to their latest code, and sometimes I let mine get pretty far out-of-sync.  It's only necessary to update when the actual DAT tables I use change format.

**Comment by Akurosia** [comment]
Just to let you know, i made now a local script which translate the created data.js to German so i can use it a little bit more efficiantly. But i think for the future an official translation feature would be good.

Is there also an official way for suggestions/ new features to the app?

**Comment by icykoneko** [comment]
I don't mind using the GitHub for requests.  The feedback page on the website is also good.  I don't expect most people would know to look for it on GitHub, and I wasn't really going to advertise it

**Comment by icykoneko** [comment]
So, got another person asking for this as well.  Like I mentioned, it should be pretty straightforward to implement, it's just extra data.  Until the site is hosted here, I need to keep everything to as few GET's as possible.

**Comment by icykoneko** [comment]
In the localization branch, I've added support for the names.  Switching languages involves setting `?lang=[en|jp|de|fr]`.  That seems like the easiest solution for now.
