### ISSUE TITLE
Missing Status images in sprite.png, when try to create it myself

### ISSUE THREAD

**Issue by Akurosia** [icykoneko/ff14-fish-tracker-app#10]
Steps to reproduce:

1. Clone git recursivly
2. Edit the game path in "manageFishData.py"
3. Create folder in /private/images/ for fish_n_tackle and weather (Script will throw errors otherwise)
4. Run from either CMD or Powershell: "py ./private/manageFishData.py rebuild -i ./private/fishData.yaml -o ./js/app/data.js --with-icons"
5. Run from either CMD or Powershell: sprity create ./public/images/ ./private/images/**/*.png -c . -s sprite.css --prefix sprite-icon --margin 2 --orientation binary-tree --engine jimp
6. Load index.html and verify e.g. "Nepto Dragon"

Actual result: There is no image displayed for intuition, but entries can be found inside the class attribute (ui middle aligned status-icon sprite-icon sprite-icon-status-intuition). Neither are there status images inside any folder nor on the created sprite sheet (compared mine and the public one for your hosted version)

Expected: Everything is created fine without errors

**Comment by icykoneko** [comment]
This stems from my not wanting to upload the image resources I'm afraid.  I will add another, initialization script, that will extract the action and status icons needed.

**Comment by icykoneko** [comment]
Try latest code, 5d5c1ea711062ccd27aabdc6abc1bc6281e20a5f

**Comment by Akurosia** [comment]
Ok it works like a charm :)
is there a way to merge it into the manage fish data file somehow?
