### ISSUE TITLE
Fish windows not ending on X:00 show as available until the hour is up

### ISSUE THREAD

**Issue by emerald000** [icykoneko/ff14-fish-tracker-app#149]
![Bug](https://i.imgur.com/izyhVXt.gif)

As you can see, the window should have ended at 3:20, but was still shown as available after it. The time to window close was also counting up. The window correctly "closed" at 4:00.

**Comment by DuvoisinNicolas** [comment]
Happened to me too, multiple times

**Comment by icykoneko** [comment]
Definitely is a bug.  The "Availability" column is controlled by the "countdown" timer events which occur every second; however, it assumes none of the fish have any expired "catchableRange" entries left.  The pruning of expired ranges only happens on each bell (Eorzean hour), thus the display glitch.

Fixing this shouldn't be too difficult, but I'm pretty sure I designed it this way for efficiency, so I'm going to try and rework the events for tracking when a fish's window closes.  For now, it doesn't appear there's any issues with off-hour opening times at least...
