### ISSUE TITLE
Availability window text disappears on pinned intuition fish

### ISSUE THREAD

**Issue by emerald000** [icykoneko/ff14-fish-tracker-app#150]
I pinned Warden of the Seven Hues before its window opened. At some point after the window fully closed, it looked like that:

![pinned](https://user-images.githubusercontent.com/4655664/232403822-52a8a065-a744-4e2b-a3cb-60035fc2db43.png)

Unpinning the Warden correctly made the text reappear.

**Comment by emerald000** [comment]
It can also happen while unpinned, in which case pinning fixes it.

![firefox_jjp0i7yHR7](https://user-images.githubusercontent.com/4655664/233796365-50982200-23e7-4f31-90a2-9ae103dd059d.png)

**Comment by blandcr** [comment]
I'm not sure if this helps but it looks like what's happening is the Intuition Fish don't get the `fish-availability-transitioning` class toggled off properly, which I suspect is due to the layout not being told to run a sort on the fish list for availability changes on Intuition Fishes.
