### ISSUE TITLE
Bait tally stuff

### ISSUE THREAD

**Issue by Vaylann** [icykoneko/ff14-fish-tracker-app#160]
![p1](https://github.com/icykoneko/ff14-fish-tracker-app/assets/88356472/f7755412-2c92-4c95-bc5c-79295c1c0248)

![Screenshot 2024-06-27 185315](https://github.com/icykoneko/ff14-fish-tracker-app/assets/88356472/acd1dd05-eb38-45cb-994e-c725f5f9b35a)

https://greasyfork.org/en/scripts/499083-fish-tally/code

**Comment by icykoneko** [comment]
Yo, that's really slick looking.  What if, it worked like the tacklebox icon does for Fish Trains, but instead of showing the limited info I currently display, if used this format?  As a popup.  Lemme know if you'd be interested in taking a go at it.  The icon could be next to the fish eyes icon so it's always available to click on.

See `trainpass/index.html#144` for example I used there.

**Comment by Vaylann** [comment]
Is that a valid train pass? It says it's not. I see what you mean though.

What IDE/software do I need to work on this? (I'm on windows)

**Comment by Vaylann** [comment]
![image](https://github.com/user-attachments/assets/65ef3b45-ec2f-4abb-b4a2-4300e9ef17be)

Was able to recreate this via some edits to index.html and viewmodel.js.

**Comment by icykoneko** [comment]
Oh nice.  I see the button up in the menu too.  I guess the text is alright, I tend to keep it to icons only cause it might not fit on mobile.  (I typically run the site on desktop, and so do most of the users anyways.)  Those are definitely the right files to edit, I'm looking forward to reviewing the pull request ^_^

**Comment by Vaylann** [comment]
Errr... yes let me shrink the "view bait" button first because it's absolutely huge.
Also I need to re-indent stuff to match the existing code.
That's a great point about mobile devices - I'll have to see if I can get the text column to hide on a narrow display.

The code is kinda shoddy because I'm not familiar with javascript, so my apologies in advance.

**Comment by icykoneko** [comment]
Just something to note, having looked at the Greasyfork implementation you wrote so far.  I'd like this to utilize the existing APIs (`FishEntry`, etc.) found in viewmodel.js and be template based if possible (using the [doT.js](https://github.com/olado/doT) templates which are used for other HTML generation.)

Hopefully that's doable, it sounded like you were already on the right track.

**Comment by icykoneko** [comment]
Merged via #164
I've also updated the fish train page to utilize the same system!
