### ISSUE TITLE
Fish are not loading.

### ISSUE THREAD

**Issue by icykoneko** [icykoneko/ff14-fish-tracker-app#17]
Seems to be related to localization merge.

**Comment by icykoneko** [comment]
I ran a few experiments last night.  It definitely appears the issues are stemming from changes made in the localization branch, and seems to be affecting the `Fish` class constructor?  Interestingly though, I can display the `Fish` class, but when I converted the lines that assign `Fishes` into a function call, I wasn't able to reference that function.
https://github.com/icykoneko/ff14-fish-tracker-app/blob/ae0f891f73c5ecaf3210d2da086d7ae157429ba5/js/app/fish.js#L194-L198

For now, I only know of the iPhone Chrome browser being affected by this issue.  Firefox appears to be fine now.

**Comment by Akurosia** [comment]
tried latest commit and for me it is still not working on Firefox

**Comment by icykoneko** [comment]
Is that on desktop or phone? Was there any error message?

**Comment by icykoneko** [comment]
Ok, that last commit did fix iPhone Safari browser.  And, apparently Chrome too.  All I can think of is something haywire with caching.

**Comment by Akurosia** [comment]
Ok i gave it another try, and now its working.

**Comment by icykoneko** [comment]
Ok, considering this fixed then.  Caching is such a pain in the butt...
