### ISSUE TITLE
Display folklore tome if required

### ISSUE THREAD

**Issue by icykoneko** [icykoneko/ff14-fish-tracker-app#23]
Because so many keep asking for it...

This should appear as an icon, either next to the fish, or in the catch path similar to fish eyes, and intuition.  Hovering should display the tome name (though it should be obvious given the fish's location.)

**Comment by Akurosia** [comment]
would you prefere the same icon as they use in ff14angler or just an icon from a "tome of ichthyological folklore"? The later one is easy to optain but the first one is part of an icon in "uld" and i dont think you could obtain it with saint that easily.
Attached you can find an image what i already have so far:
![vivaldi_Vc6QQxlpCx](https://user-images.githubusercontent.com/7465469/58951474-843b5780-8791-11e9-8a81-28deac3d9980.png)

**Comment by icykoneko** [comment]
It looks like we can get the exact book icon by following:
`FishParameter.GatheringSubCategory.Item.Icon`.
For the tooltip, I would use `FishParameter.GatheringSubCategory.FolkloreBook`.

But, I also kinda like the smaller icon idea on the left side.  I found another icon under the MAP_MARKER_FATE_OBJECT category. ![060556](https://user-images.githubusercontent.com/28579746/58954664-d36c9280-8767-11e9-9cd6-8f021506e6db.png)  It's a tad bigger though.
