### ISSUE TITLE
CompletionManager

### ISSUE THREAD

**Issue by Airex** [icykoneko/ff14-fish-tracker-app#24]
Is not it better to keep completed and pinned as {} and work with keys as set this O(1) for contains operations instead of O(n), this can improve performance when many of fishes are already caught

**Comment by icykoneko** [comment]
Yea, that would help. Shouldn't be too disruptive of a change I think.

**Comment by icykoneko** [comment]
Really, this should be broken out of the viewmodel.
Also, consider addressing this with #14.
