### ISSUE TITLE
Intuition fish names do not update when changing language

### ISSUE THREAD

**Issue by icykoneko** [icykoneko/ff14-fish-tracker-app#32]
![image](https://user-images.githubusercontent.com/28579746/59807439-e5047d00-92c5-11e9-9ec3-6b66e68ab61f.png) ![image](https://user-images.githubusercontent.com/28579746/59807468-05343c00-92c6-11e9-9a37-f30d93c99889.png)

All the other names update, but not the intuition fish.

**Comment by Akurosia** [comment]
This is strange as it works for me (see attached image)
![vivaldi_61mOeak5Lf](https://user-images.githubusercontent.com/7465469/59825201-ad341e80-9333-11e9-946a-5194e9464a4e.png)

**Comment by icykoneko** [comment]
When you open the page it is correct, but if you change the language afterwards, it doesn’t update.

**Comment by Akurosia** [comment]
Nope even works for me when page is opened and i switch languages afterwards.
See attached video.
[IRcQoaSfB0.zip](https://github.com/icykoneko/ff14-fish-tracker-app/files/3313220/IRcQoaSfB0.zip)

**Comment by icykoneko** [comment]
Strange, I'm able to trigger it all the time on mine.  But on my phone, I had to filter to a single patch to trigger it.  So, I think there might be something else at play here.  Possibly a race condition.

**Comment by icykoneko** [comment]
This should be fixed at this point.  I now have explicit code which is updating this information.
