### ISSUE TITLE
z-index for .tug-indicator

### ISSUE THREAD

**Issue by leewdch** [icykoneko/ff14-fish-tracker-app#60]
Can you please add a higher z-index for `.tug-indicator` so that it's easily readable and not hidden when icons are overlapping? Some time the arrangement of icons is so compact the icon is completely covered
![image](https://user-images.githubusercontent.com/60162875/77260156-8e7a0400-6c86-11ea-96bb-589cd213f70b.png)
![image](https://user-images.githubusercontent.com/60162875/77260162-9afe5c80-6c86-11ea-81f1-0d00d646e9a4.png)

`.tug-indicator {z-index:2;}`

**Comment by icykoneko** [comment]
This is using Firefox right? It’s actually a problem with how I’m making those images. I used the `zoom` style but that’s not supported by Firefox.

I’ve got another potential solution though. Working on the fish guide today, I experimented with the `transform` style.

Thanks for bringing this up, I’ll try getting to this soon.

**Comment by icykoneko** [comment]
Alright, I've got a fix in the works for this.  It should solve both issues (Firefox, and the overlapping)

**Comment by icykoneko** [comment]
From Firefox:
![stylesheet-rules-fix](https://user-images.githubusercontent.com/28579746/77388862-b4c3a080-6d67-11ea-8963-c8cc9c5b0cf8.png)
And from Chrome:
![stylesheet-rules-fix-chrome](https://user-images.githubusercontent.com/28579746/77388946-fd7b5980-6d67-11ea-85c9-0c946431a5be.png)

Keep in mind, these are using narrow width screen size, but I think this should solve the issues.

**Comment by leewdch** [comment]
Thank you. I can now see the changes on Firefox as well. Guess I can close this one.
