### ISSUE TITLE
Filter 5.3 does not show fish from 5.35

### ISSUE THREAD

**Issue by Akurosia** [icykoneko/ff14-fish-tracker-app#67]
I was trying to filter for the new fish added in 5,35 but could not find it even when setting the filter to just show 5.3 fish.
The only way i was able to see the fish was, when i added its ID to the pinned field while importing data. The name i tried in detail was "Allagan Hunter" and the ID used was "31134"

**Comment by icykoneko** [comment]
Gaaah, thanks.  I think adjusting the `isFishFiltered` function will solve this if I check it as a string with one decimal place.
