### ISSUE TITLE
calculate the mathematical average uptime instead of using a lot of windows

### ISSUE THREAD

**Issue by rexatlanti** [icykoneko/ff14-fish-tracker-app#7]
Calculating over 3000 windows at times to get an uptime is kinda excessive if you could just go by weather rate

```javascript
// up equals number of hours it's up. Eg 8-16 ET = 8
const uptime = up/24
if (dependentOnWeather) {
     //weather being an array of weather the fish is up for
     var rate = 0
     weather.forEach( function(weathers) {
         rate += weatherRate(weathers) * uptime
     }
     uptime = rate
}
if (dependsOnTransition) {
    //initWeather = array of initial weather, transitionWeather = array of weather we need to transition to
    var rate = 0
    transitionWeather.forEach( function(transitionWeathers) {
        initWeather.forEach( function(initWeathers) {
            rate += weatherRate(initWeathers) * weatherRate(transitionWeathers) * uptime
        }
    }
    uptime = rate
}
return uptime
```
(just an outline. I hope you can use forEach like this ;u; )

**Comment by icykoneko** [comment]
Thanks, hopefully this will cut down on the overall calculations.
For `weatherRate`, is that the rate at which the particular weather is possible in the zone?

Also, knowing that the weather can only change every 8 hours, does that impact your formula?

**Comment by rexatlanti** [comment]
weatherRate would be the rate a weather occurs in a zone. Each weather has a distinct probability to occur.

For the second part imagine a fishy that's up from 7-10 ET and needs fair skies. Let fair skies have a probability of 10%.

Then our fish would be up for 1h ET in weather window 1 and for 2h in weather window 2. The windows are independent. The total uptime would thus be
`1/8 * 0.1 + 2/8 * 0.1 = 3/8 * 0.1 = 3/24 * 3 * 0.1`
So yea I didn't take the change rate into account, gomen. Lemme rewrite the code snipped to reflect that:
```javascript
// up equals number of hours it's up. Eg 8-16 ET = 8
const uptime = up/24
if (dependentOnWeather) {
     //weather being an array of weather the fish is up for
     var rate = 0
     weather.forEach( function(weathers) {
         rate += weatherRate(weathers) * uptime
     }
     uptime = 3 * rate
}
if (dependsOnTransition) {
    //initWeather = array of initial weather, transitionWeather = array of weather we need to transition to
    var rate = 0
    transitionWeather.forEach( function(transitionWeathers) {
        initWeather.forEach( function(initWeathers) {
            rate += weatherRate(initWeathers) * weatherRate(transitionWeathers) * uptime
        }
    }
    uptime = 3 * rate
}
return uptime
```

**Comment by icykoneko** [comment]
Since the site now includes the list of the next 10 windows, and users like this feature, I'm gonna leave the rarity calculation as is.  The one interesting benefit to always computing it is, while the weather pattern rate does remain constant, it could be possible for a not-so-rare fish to suddenly become super rare (i.e. that 22-day drought for Ruby Dragon a month ago.)
